package br.unesp.fc.signer.view;

import br.unesp.fc.signer.SignerWork;
import br.unesp.fc.signer.model.SignModel;
import java.security.KeyStoreException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;

@Component
public class MainFrame extends javax.swing.JFrame {

    private final SignModel signModel;

    private SignerWork signerWork;

    /**
     * Creates new form Main
     */
    public MainFrame(LeftPanel leftPanel, ViewPanel viewPanel, SignModel signModel) {
        initComponents();
        jSplitPane1.setLeftComponent(leftPanel);
        jSplitPane1.setRightComponent(viewPanel);
        jSplitPane1.setDividerLocation(255);
        pack();
        this.signModel = signModel;
    }

    @Autowired
    public void setSignerWork(@Lazy SignerWork signerWork) {
        this.signerWork = signerWork;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Assinador");
        setIconImage(new javax.swing.ImageIcon(this.getClass().getResource("/icons/main.png")).getImage());
        setPreferredSize(new java.awt.Dimension(1024, 768));

        jMenu1.setText("Arquivo");

        jMenuItem2.setText("Assinar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");

        jMenuItem1.setText("Sobre");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        About about = new About(this, true);
        about.setLocation(this.getX() + (this.getWidth() - about.getWidth()) / 2, this.getY() + (this.getHeight() - about.getHeight()) / 2);
        about.setVisible(true);
        about.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        SignDialog signDialog = new SignDialog(this, true, signModel);
        signDialog.setLocation(this.getX() + (this.getWidth() - signDialog.getWidth()) / 2, this.getY() + (this.getHeight()- signDialog.getHeight()) / 2);
        signDialog.setVisible(true);
        signDialog.dispose();
        if (signModel.getCertificate() != null) {
            try {
                signerWork.run();
            } catch (KeyStoreException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
