package br.unesp.fc.signer.view;

import br.unesp.fc.signer.model.PdfViewModel;
import br.unesp.fc.signer.model.SignVerifyInfoModel;
import java.awt.BorderLayout;
import java.io.IOException;
import org.springframework.stereotype.Component;

@Component
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form View
     */
    public ViewPanel(PdfPanel pdfPanel, BottomPanel bottomPanel) {
        initComponents();
        jScrollPane1.setViewportView(pdfPanel);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
        jScrollPane1.getHorizontalScrollBar().setUnitIncrement(16);
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(bottomPanel, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public static void main(String arg[]) throws IOException {
        br.unesp.fc.signer.Signer.setup();
        var fileModel = new br.unesp.fc.signer.model.FileModel(new java.io.File("/home/demitrius/NetBeansProjects/SignTest/sample.pdf"));
//        var fileModel = new br.unesp.fc.signer.model.FileModel(new java.io.File("/home/demitrius/NetBeansProjects/SignTest/certificado-test1.pdf"));
        javax.swing.SwingUtilities.invokeLater(() -> {
            PdfPanel pdfPanel = new PdfPanel();
            BottomPanel bottomPanel = new BottomPanel();
            ViewPanel viewPanel = new ViewPanel(pdfPanel, bottomPanel);
            PdfViewModel viewModel = new PdfViewModel();
            SignVerifyInfoModel signVerifyModel = new SignVerifyInfoModel();
            //signVerifyModel.setBackground(Color.LIGHT_GRAY);
//            model.setNumberPages(2);
//            model.setCurrentPage(0);
            viewModel.setPage(0, 1);
            viewModel.setScale(1.5f);
            signVerifyModel.setRotation(90);
            pdfPanel.setPdfViewModel(viewModel);
            pdfPanel.setSignVerifyInfoModel(signVerifyModel);
            bottomPanel.setPdfViewModel(viewModel);
            pdfPanel.setFileModel(fileModel);
            var frame = new javax.swing.JFrame();
            frame.add(viewPanel);
            frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
            frame.setPreferredSize(new java.awt.Dimension(1024, 768));
            frame.pack();
            frame.setVisible(true);
        });
    }
}
